spring.application.name=ccp



# DB Connection
spring.datasource.url=jdbc:mysql://localhost:3306/careerpro?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root123

# Hibernate Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Server Port
server.port=8081